# -*- coding: utf-8 -*-
"""AI Pro_Light GBM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H9icGnBvnEos4qVrI0P-YASnkgRhcu0k
"""

# Install LightGBM (only needed in Colab)
!pip install lightgbm

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn import metrics
from lightgbm import LGBMRegressor

"""Load dataset

"""

data = pd.read_csv("/content/sample_data/1 data.csv")

print(data.head())
print("Columns:", data.columns)

"""Clean data"""

data = data.dropna()

data.columns = ['Frequency', 'S11']

X = data[['Frequency']]
y = data['S11']

"""Light GBM_Changing"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


model = LGBMRegressor(n_estimators=150)
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Metrics
mae = metrics.mean_absolute_error(y_test, y_pred)
mse = metrics.mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = metrics.r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

plt.figure()

# Actual values (blue dots)
plt.scatter(X_test, y_test, label="Actual")

# Predicted values (orange dots)
plt.scatter(X_test, y_pred, label="Predicted")

plt.xlabel("Frequency")
plt.ylabel("S11 (dB)")
plt.title("Model Accuracy (LightGBM)")

plt.legend()
plt.grid()

plt.show()

"""Bandwidth"""

data['Frequency_Hz'] = data['Frequency'] * 1e12

valid = data[data['S11'] <= -10]

f_min = valid['Frequency_Hz'].min()
f_max = valid['Frequency_Hz'].max()

bandwidth = f_max - f_min

print("Minimum Frequency (Hz):", f_min)
print("Maximum Frequency (Hz):", f_max)
print("Bandwidth (Hz):", bandwidth)

"""S11 Frequency"""

plt.plot(data['Frequency'], data['S11'])
plt.axhline(y=-10, linestyle='--')
plt.xlabel("Frequency (THz)")
plt.ylabel("S11 (dB)")
plt.title("S11 vs Frequency")
plt.show()

center_freq = (f_max + f_min) / 2
fractional_bw = bandwidth / center_freq

print("Fractional Bandwidth:", fractional_bw)

"""Loss"""

data['Reflection_Coefficient'] = 10 ** (data['S11'] / 20)
data['Reflected_Power_%'] = (data['Reflection_Coefficient'] ** 2) * 100
data['Transmission_Efficiency_%'] = 100 - data['Reflected_Power_%']

plt.plot(data['Frequency'], data['Reflected_Power_%'])
plt.xlabel("Frequency (THz)")
plt.ylabel("Reflected Power (%)")
plt.title("Reflected Power Loss vs Frequency")
plt.show()

"""VSWR"""

data['VSWR'] = (
    (1 + data['Reflection_Coefficient']) /
    (1 - data['Reflection_Coefficient'])
)

print(data[['Frequency', 'VSWR']].head())

plt.plot(data['Frequency'], data['VSWR'])
plt.xlabel("Frequency (THz)")
plt.ylabel("VSWR")
plt.title("VSWR vs Frequency")
plt.show()