# -*- coding: utf-8 -*-
"""AI Pro_XG Boost

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11P-UWFjumRBIbbVYkT1E0EPFqiBMsCP7
"""

!pip install xgboost

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn import metrics
from xgboost import XGBRegressor

"""Loading dataset"""

data = pd.read_csv("/content/sample_data/1 data.csv")

print("First 5 rows:\n", data.head())
print("\nColumns:", data.columns)

data = data.dropna()
data.columns = ['Frequency', 'S11']

X = data[['Frequency']]
y = data['S11']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = XGBRegressor(n_estimators=150, verbosity=0)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
mae = metrics.mean_absolute_error(y_test, y_pred)
mse = metrics.mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = metrics.r2_score(y_test, y_pred)

print("\n--- MODEL PERFORMANCE ---")
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

sorted_indices = X_test['Frequency'].argsort()

X_test_sorted = X_test.iloc[sorted_indices]
y_test_sorted = y_test.iloc[sorted_indices]
y_pred_sorted = y_pred[sorted_indices]

plt.figure()

# Actual (blue)
plt.scatter(X_test_sorted.values, y_test_sorted.values, label="Actual")

# Predicted (orange)
plt.scatter(X_test_sorted.values, y_pred_sorted, label="Predicted")

plt.xlabel("Frequency")
plt.ylabel("S11 (dB)")
plt.title("Model Accuracy (XGBoost)")

plt.legend()
plt.grid()

plt.show()

"""Bandwidth"""

data['Frequency_Hz'] = data['Frequency'] * 1e12

valid = data[data['S11'] <= -10]

f_min = valid['Frequency_Hz'].min()
f_max = valid['Frequency_Hz'].max()

bandwidth = f_max - f_min

print("\n--- BANDWIDTH ---")
print("Minimum Frequency (Hz):", f_min)
print("Maximum Frequency (Hz):", f_max)
print("Bandwidth (Hz):", bandwidth)

"""S11 Graph"""

plt.plot(data['Frequency'], data['S11'])
plt.axhline(y=-10, linestyle='--')
plt.xlabel("Frequency (THz)")
plt.ylabel("S11 (dB)")
plt.title("S11 vs Frequency")
plt.show()

"""Fractional Bandwidth"""

center_freq = (f_max + f_min) / 2
fractional_bw = bandwidth / center_freq

print("Fractional Bandwidth:", fractional_bw)

"""Loss"""

data['Reflection_Coefficient'] = 10 ** (data['S11'] / 20)
data['Reflected_Power_%'] = (data['Reflection_Coefficient'] ** 2) * 100
data['Reflected_Power_%'] = (data['Reflection_Coefficient'] ** 2) * 100

plt.plot(data['Frequency'], data['Reflected_Power_%'])
plt.xlabel("Frequency (THz)")
plt.ylabel("Reflected Power (%)")
plt.title("Reflected Power Loss vs Frequency")
plt.show()

"""VSWR"""

data['VSWR'] = (
    (1 + data['Reflection_Coefficient']) /
    (1 - data['Reflection_Coefficient'])
)

print("\n--- VSWR SAMPLE ---")
print(data[['Frequency', 'VSWR']].head())

plt.plot(data['Frequency'], data['VSWR'])
plt.xlabel("Frequency (THz)")
plt.ylabel("VSWR")
plt.title("VSWR vs Frequency")
plt.show()

"""SNR Caluculation(approx)"""

# Convert S11 (dB) to linear reflection coefficient
data['Reflection_Coefficient'] = 10 ** (data['S11'] / 20)

# Reflected power (noise-like component)
data['Noise_Power'] = (data['Reflection_Coefficient'] ** 2)

# Signal power (remaining power)
data['Signal_Power'] = 1 - data['Noise_Power']

# SNR Calculation
data['SNR'] = data['Signal_Power'] / data['Noise_Power']

# Convert to dB
data['SNR_dB'] = 10 * np.log10(data['SNR'])

print(data[['Frequency', 'SNR_dB']].head())

plt.plot(data['Frequency'], data['SNR_dB'])
plt.xlabel("Frequency (THz)")
plt.ylabel("SNR (dB)")
plt.title("Estimated SNR vs Frequency")
plt.grid()
plt.show()